/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leepood_bsdiff_tools_PatchTools */

#ifndef _Included_org_hyxf_bsdiff_PatchTools
#define _Included_org_hyxf_bsdiff_PatchTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hyxf_bsdiff_PatchTools
 * Method:    applay_patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_hyxf_bsdiff_PatchTools_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
